sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
env:
  global:
    - CRAN_REPO=https://cran.rstudio.com
matrix:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    services:
      - xvfb
    before_install:
      - Rscript -e 'install.packages(c("ggplot2", "quickPlot", "reproducible"), type = "source")'
    r_binary_packages:
      - BH
      - dplyr
      - git2r
      - igraph
      - raster
      - RSQlite
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    services:
      - xvfb
    before_install:
      - Rscript -e 'install.packages(c("ggplot2", "quickPlot"), type = "source")'
    r_binary_packages:
      - BH
      - dplyr
      - git2r
      - igraph
      - raster
      - RSQlite
    r_packages:
      - covr
      - devtools
      - rgdal
      - rgeos
    r_github_packages:
      - jimhester/lintr
    after_success:
      - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    r: devel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libgit2-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    services:
      - xvfb
    before_install:
      - Rscript -e 'install.packages(c("ggplot2", "quickPlot"), type = "source")'
    r_binary_packages:
      - BH
      - dplyr
      - git2r
      - igraph
      - raster
      - RSQlite
    r_packages:
      - devtools
      - rgdal
      - rgeos
  - os: osx
    osx_image: xcode9.4
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_script:
      - Rscript -e "install.packages(c('rgdal', 'rgeos'), type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
